name: sync

on:
    push:
      branches:
      - master  # Set a branch to deploy
    pull_request:
      branches:
      - master  # Set a branch to deploy
    workflow_dispatch:
    schedule:
        # Runs everyday at 0:00 AM
        - cron: "0 0 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
            - name: Sync cnblog
              run: |
                git checkout cnblog
                cd gh/leegical
                rm -rf Blog_img
                git clone https://github.com/leegical/Blog_img.git
                cd Blog_img
                rm -rf .git*
      
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                branch: cnblog
                commit_message: ':arrow_up: sync cnblog img with master'
                commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
                push_options: '--set-upstream'